/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GdkPixbuf *window1_icon_pixbuf;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label45;
  GtkWidget *image18;
  GtkWidget *button1;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *label54;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("my gym"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window1), 758, 581);
  gtk_window_set_resizable (GTK_WINDOW (window1), FALSE);
  window1_icon_pixbuf = create_pixbuf ("sdsdsds.png");
  if (window1_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window1), window1_icon_pixbuf);
      gdk_pixbuf_unref (window1_icon_pixbuf);
    }

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);
  gtk_widget_set_size_request (fixed1, 758, 582);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 16, 152);
  gtk_widget_set_size_request (entry1, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 16, 240);
  gtk_widget_set_size_request (entry2, 224, 32);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label2 = gtk_label_new (_("LOGIN"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 24, 128);
  gtk_widget_set_size_request (label2, 81, 32);

  label3 = gtk_label_new (_("PASSWORD"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 32, 208);
  gtk_widget_set_size_request (label3, 81, 21);

  label4 = gtk_label_new ("");
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 244, 546);
  gtk_widget_set_size_request (label4, 284, 40);

  label45 = gtk_label_new ("<span foreground=\"#8cdc8c\" size=\"large\">Welcome to my gym</span>");
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed1), label45, 1, 549);
  gtk_widget_set_size_request (label45, 191, 35);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);
  gtk_label_set_width_chars (GTK_LABEL (label45), 56);

  image18 = create_pixmap (window1, "gyym.jpg");
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed1), image18, 0, 0);
  gtk_widget_set_size_request (image18, 769, 557);
  gtk_misc_set_alignment (GTK_MISC (image18), 0.22, 0.67);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 8, 304);
  gtk_widget_set_size_request (button1, 232, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button1), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  label54 = gtk_label_new_with_mnemonic (_("<span foreground=\"#000000\" size=\"x-large\" >CONNECT</span>"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox6), label54, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  g_signal_connect ((gpointer) window1, "activate_default",
                    G_CALLBACK (on_window1_activate_default),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, label45, "label45");
  GLADE_HOOKUP_OBJECT (window1, image18, "image18");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1, label54, "label54");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GdkPixbuf *window2_icon_pixbuf;
  GtkWidget *fixed3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *image22;
  GtkWidget *combobox1;
  GtkWidget *button12;
  GtkWidget *image10;
  GtkWidget *button8;
  GtkWidget *image6;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *label49;
  GtkWidget *label18;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window2, 758, 581);
  gtk_window_set_title (GTK_WINDOW (window2), _("my gym"));
  gtk_window_set_position (GTK_WINDOW (window2), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window2), 758, 581);
  gtk_window_set_resizable (GTK_WINDOW (window2), FALSE);
  window2_icon_pixbuf = create_pixbuf ("sdsdsds.png");
  if (window2_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window2), window2_icon_pixbuf);
      gdk_pixbuf_unref (window2_icon_pixbuf);
    }

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window2), fixed3);
  gtk_container_set_border_width (GTK_CONTAINER (fixed3), 42);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 120, 112);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry4), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entry4), _("newpass"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 120, 168);
  gtk_widget_set_size_request (entry5, 157, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 120, 232);
  gtk_widget_set_size_request (entry6, 160, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  image22 = create_pixmap (window2, "gyym.jpg");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed3), image22, 400, -48);
  gtk_widget_set_size_request (image22, 316, 593);
  gtk_misc_set_alignment (GTK_MISC (image22), 0.41, 0.28);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox1, 144, 296);
  gtk_widget_set_size_request (combobox1, 126, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Dance"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Aerobic"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Zumba"));

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed3), button12, 168, 360);
  gtk_widget_set_size_request (button12, 74, 29);

  image10 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (button12), image10);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed3), button8, 8, 448);
  gtk_widget_set_size_request (button8, 66, 29);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (button8), image6);

  label46 = gtk_label_new (_("<span foreground=\"#000000\" size=\"large\">nom</span>"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed3), label46, 16, 160);
  gtk_widget_set_size_request (label46, 102, 38);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  label47 = gtk_label_new (_("<span foreground=\"#000000\" size=\"large\">num tel</span>"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed3), label47, 16, 224);
  gtk_widget_set_size_request (label47, 102, 38);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  label48 = gtk_label_new (_("<span foreground=\"#000000\" size=\"large\">sp\303\251cialit\303\251</span>"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed3), label48, 24, 296);
  gtk_widget_set_size_request (label48, 102, 38);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  label49 = gtk_label_new (_("<span foreground=\"#000000\" size=\"large\" font=\"Helvetica\" >Modification de profile</span>"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed3), label49, 104, 32);
  gtk_widget_set_size_request (label49, 192, 48);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  label18 = gtk_label_new (_("<span foreground=\"#000000\" size=\"large\" >PASSWORD</span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 16, 104);
  gtk_widget_set_size_request (label18, 102, 38);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window2, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window2, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window2, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window2, image22, "image22");
  GLADE_HOOKUP_OBJECT (window2, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window2, button12, "button12");
  GLADE_HOOKUP_OBJECT (window2, image10, "image10");
  GLADE_HOOKUP_OBJECT (window2, button8, "button8");
  GLADE_HOOKUP_OBJECT (window2, image6, "image6");
  GLADE_HOOKUP_OBJECT (window2, label46, "label46");
  GLADE_HOOKUP_OBJECT (window2, label47, "label47");
  GLADE_HOOKUP_OBJECT (window2, label48, "label48");
  GLADE_HOOKUP_OBJECT (window2, label49, "label49");
  GLADE_HOOKUP_OBJECT (window2, label18, "label18");

  gtk_widget_grab_default (combobox1);
  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GdkPixbuf *window3_icon_pixbuf;
  GtkWidget *fixed4;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *calendar1;
  GtkWidget *button7;
  GtkWidget *image5;
  GtkWidget *label27;
  GtkWidget *button6;
  GtkWidget *label34;
  GtkWidget *combobox2;
  GtkWidget *image23;
  GtkWidget *label50;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window3, 785, 581);
  gtk_window_set_title (GTK_WINDOW (window3), _("my gym"));
  gtk_window_set_position (GTK_WINDOW (window3), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window3), 758, 581);
  gtk_window_set_resizable (GTK_WINDOW (window3), FALSE);
  window3_icon_pixbuf = create_pixbuf ("sdsdsds.png");
  if (window3_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window3), window3_icon_pixbuf);
      gdk_pixbuf_unref (window3_icon_pixbuf);
    }

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window3), fixed4);

  spinbutton1_adj = gtk_adjustment_new (31, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton1, 72, 120);
  gtk_widget_set_size_request (spinbutton1, 64, 24);

  spinbutton2_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2, 176, 120);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (2018, 2018, 2030, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton3, 288, 120);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label23 = gtk_label_new (_("jour"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 80, 88);
  gtk_widget_set_size_request (label23, 49, 17);

  label24 = gtk_label_new (_("mois"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 176, 88);
  gtk_widget_set_size_request (label24, 49, 17);

  label25 = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 288, 88);
  gtk_widget_set_size_request (label25, 49, 17);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed4), calendar1, 0, 328);
  gtk_widget_set_size_request (calendar1, 432, 256);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed4), button7, 24, 16);
  gtk_widget_set_size_request (button7, 66, 29);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (button7), image5);

  label27 = gtk_label_new (_("heure"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed4), label27, 88, 208);
  gtk_widget_set_size_request (label27, 49, 17);

  button6 = gtk_button_new_with_mnemonic (_("comfirmer"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed4), button6, 160, 272);
  gtk_widget_set_size_request (button6, 104, 32);

  label34 = gtk_label_new ("");
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 104, 232);
  gtk_widget_set_size_request (label34, 217, 32);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox2, 152, 208);
  gtk_widget_set_size_request (combobox2, 128, 32);
  gtk_container_set_border_width (GTK_CONTAINER (combobox2), 441);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("9h==>10h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("10h==>11h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("12h==>13h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("13h==>14h"));

  image23 = create_pixmap (window3, "gym_monaghan.jpg");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed4), image23, 432, 0);
  gtk_widget_set_size_request (image23, 360, 584);
  gtk_misc_set_alignment (GTK_MISC (image23), 0.76, 1);

  label50 = gtk_label_new (_("<span foreground=\"#000000\" size=\"large\" >Ajouter un date de diponibilit\303\251</span>"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed4), label50, 96, 40);
  gtk_widget_set_size_request (label50, 240, 40);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window3, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window3, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window3, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window3, label23, "label23");
  GLADE_HOOKUP_OBJECT (window3, label24, "label24");
  GLADE_HOOKUP_OBJECT (window3, label25, "label25");
  GLADE_HOOKUP_OBJECT (window3, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (window3, button7, "button7");
  GLADE_HOOKUP_OBJECT (window3, image5, "image5");
  GLADE_HOOKUP_OBJECT (window3, label27, "label27");
  GLADE_HOOKUP_OBJECT (window3, button6, "button6");
  GLADE_HOOKUP_OBJECT (window3, label34, "label34");
  GLADE_HOOKUP_OBJECT (window3, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (window3, image23, "image23");
  GLADE_HOOKUP_OBJECT (window3, label50, "label50");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed2;
  GtkWidget *image17;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image15;
  GtkWidget *label41;
  GtkWidget *button15;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image13;
  GtkWidget *label38;
  GtkWidget *button11;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image8;
  GtkWidget *label32;
  GtkWidget *image19;
  GtkWidget *label51;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *button13;
  GtkWidget *image11;
  GtkWidget *button4;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image25;
  GtkWidget *label52;
  GtkWidget *label42;
  GtkWidget *label40;
  GtkWidget *label5;
  GtkWidget *label15;
  GtkWidget *image27;
  GtkWidget *label39;
  GtkWidget *button5;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image16;
  GtkWidget *label43;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("my gym"));
  gtk_window_set_position (GTK_WINDOW (window4), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (window4), FALSE);
  gtk_window_set_icon_name (GTK_WINDOW (window4), "gtk-about");
  gtk_window_set_gravity (GTK_WINDOW (window4), GDK_GRAVITY_CENTER);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window4), fixed2);

  image17 = create_pixmap (window4, "IMG_4383-1.jpg");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed2), image17, 0, 0);
  gtk_widget_set_size_request (image17, 216, 584);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 32, 184);
  gtk_widget_set_size_request (button3, 152, 64);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image15 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox3), image15, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("<span foreground=\"#000000\"  >Ajouter      date \nde disponibilit\303\251</span>"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox3), label41, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed2), button15, 32, 320);
  gtk_widget_set_size_request (button15, 152, 72);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button15), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image13 = gtk_image_new_from_stock ("gtk-orientation-portrait", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox2), image13, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("<span foreground=\"#000000\"  >FICHES\nMEDICALES</span>"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox2), label38, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed2), button11, 16, 544);
  gtk_widget_set_size_request (button11, 74, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button11), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image8 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox1), image8, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("logout "));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox1), label32, FALSE, FALSE, 0);

  image19 = create_pixmap (window4, "gyym.jpg");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed2), image19, 511, -8);
  gtk_widget_set_size_request (image19, 7, 589);
  gtk_misc_set_alignment (GTK_MISC (image19), 0, 0.26);

  label51 = gtk_label_new (_("<span foreground=\"#000000\" size=\"small\" >USERNAME</span>"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed2), label51, 232, 344);
  gtk_widget_set_size_request (label51, 113, 32);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  label7 = gtk_label_new (_("<span foreground=\"#000000\" size=\"small\" >NOM</span> "));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 240, 376);
  gtk_widget_set_size_request (label7, 112, 32);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  label8 = gtk_label_new (_("<span foreground=\"#000000\" size=\"small\" >TEL</span>"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 256, 408);
  gtk_widget_set_size_request (label8, 80, 40);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  label9 = gtk_label_new (_("<span foreground=\"#000000\" size=\"small\" >SPECIALITE</span>"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 240, 448);
  gtk_widget_set_size_request (label9, 88, 32);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed2), button13, 104, 544);
  gtk_widget_set_size_request (button13, 74, 29);

  image11 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_container_add (GTK_CONTAINER (button13), image11);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 304, 184);
  gtk_widget_set_size_request (button4, 144, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button4), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image25 = create_pixmap (window4, "gym_monaghan.jpg");
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox5), image25, FALSE, FALSE, 0);
  gtk_widget_set_size_request (image25, 27, 38);

  label52 = gtk_label_new_with_mnemonic (_("MODIFIER"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox5), label52, FALSE, FALSE, 0);

  label42 = gtk_label_new ("");
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed2), label42, 496, 80);
  gtk_widget_set_size_request (label42, 264, 160);

  label40 = gtk_label_new (_("___________________________\n<span foreground=\"#000000\"  size=\"large\">MES DATES DE \nDISPONIBILITE</span>\n___________________________"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed2), label40, 496, 216);
  gtk_widget_set_size_request (label40, 257, 96);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);
  gtk_label_set_justify (GTK_LABEL (label40), GTK_JUSTIFY_CENTER);

  label5 = gtk_label_new (_("___________________________\n<span foreground=\"#000000\"  size=\"large\">MES \nRENDEZ-VOUS</span>\n___________________________"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 504, 0);
  gtk_widget_set_size_request (label5, 264, 96);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_CENTER);

  label15 = gtk_label_new ("");
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 360, 352);
  gtk_widget_set_size_request (label15, 136, 120);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_CENTER);

  image27 = create_pixmap (window4, "Untitled-16556.png");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed2), image27, 256, 16);
  gtk_widget_set_size_request (image27, 416, 328);

  label39 = gtk_label_new ("");
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed2), label39, 528, 296);
  gtk_widget_set_size_request (label39, 192, 280);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 32, 248);
  gtk_widget_set_size_request (button5, 152, 72);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button5), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image16 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox4), image16, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("<span foreground=\"#000000\"  >Modifier    date\nde disponibilit\303\251</span>"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox4), label43, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window4, image17, "image17");
  GLADE_HOOKUP_OBJECT (window4, button3, "button3");
  GLADE_HOOKUP_OBJECT (window4, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window4, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window4, image15, "image15");
  GLADE_HOOKUP_OBJECT (window4, label41, "label41");
  GLADE_HOOKUP_OBJECT (window4, button15, "button15");
  GLADE_HOOKUP_OBJECT (window4, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window4, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window4, image13, "image13");
  GLADE_HOOKUP_OBJECT (window4, label38, "label38");
  GLADE_HOOKUP_OBJECT (window4, button11, "button11");
  GLADE_HOOKUP_OBJECT (window4, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window4, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window4, image8, "image8");
  GLADE_HOOKUP_OBJECT (window4, label32, "label32");
  GLADE_HOOKUP_OBJECT (window4, image19, "image19");
  GLADE_HOOKUP_OBJECT (window4, label51, "label51");
  GLADE_HOOKUP_OBJECT (window4, label7, "label7");
  GLADE_HOOKUP_OBJECT (window4, label8, "label8");
  GLADE_HOOKUP_OBJECT (window4, label9, "label9");
  GLADE_HOOKUP_OBJECT (window4, button13, "button13");
  GLADE_HOOKUP_OBJECT (window4, image11, "image11");
  GLADE_HOOKUP_OBJECT (window4, button4, "button4");
  GLADE_HOOKUP_OBJECT (window4, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window4, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window4, image25, "image25");
  GLADE_HOOKUP_OBJECT (window4, label52, "label52");
  GLADE_HOOKUP_OBJECT (window4, label42, "label42");
  GLADE_HOOKUP_OBJECT (window4, label40, "label40");
  GLADE_HOOKUP_OBJECT (window4, label5, "label5");
  GLADE_HOOKUP_OBJECT (window4, label15, "label15");
  GLADE_HOOKUP_OBJECT (window4, image27, "image27");
  GLADE_HOOKUP_OBJECT (window4, label39, "label39");
  GLADE_HOOKUP_OBJECT (window4, button5, "button5");
  GLADE_HOOKUP_OBJECT (window4, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window4, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window4, image16, "image16");
  GLADE_HOOKUP_OBJECT (window4, label43, "label43");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GdkPixbuf *window5_icon_pixbuf;
  GtkWidget *fixed5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label33;
  GtkWidget *image9;
  GtkWidget *button10;
  GtkWidget *image7;
  GtkWidget *button9;
  GtkWidget *treeview1;
  GtkWidget *label55;
  GtkWidget *button18;
  GtkWidget *image28;
  GtkWidget *label31;
  GtkWidget *image29;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window5, 768, 584);
  gtk_window_set_title (GTK_WINDOW (window5), _("my gym"));
  gtk_window_set_resizable (GTK_WINDOW (window5), FALSE);
  window5_icon_pixbuf = create_pixbuf ("sdsdsds.png");
  if (window5_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window5), window5_icon_pixbuf);
      gdk_pixbuf_unref (window5_icon_pixbuf);
    }

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5), fixed5);

  spinbutton6_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton6, 168, 56);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label29 = gtk_label_new (_("numero de date"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed5), label29, 24, 56);
  gtk_widget_set_size_request (label29, 113, 24);

  label30 = gtk_label_new (_("modifier une date"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 136, 16);
  gtk_widget_set_size_request (label30, 128, 24);

  label33 = gtk_label_new ("");
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 104, 104);
  gtk_widget_set_size_request (label33, 177, 24);

  image9 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed5), image9, 120, 104);
  gtk_widget_set_size_request (image9, 37, 45);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed5), button10, 24, 8);
  gtk_widget_set_size_request (button10, 74, 29);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (button10), image7);

  button9 = gtk_button_new_with_mnemonic (_("comfirmer"));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed5), button9, 304, 40);
  gtk_widget_set_size_request (button9, 154, 37);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 56, 208);
  gtk_widget_set_size_request (treeview1, 400, 368);

  label55 = gtk_label_new (_("<span foreground=\"#000000\" size=\"x-large\">\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n</span>"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed5), label55, 12, 206);
  gtk_widget_set_size_request (label55, 57, 325);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);
  gtk_label_set_justify (GTK_LABEL (label55), GTK_JUSTIFY_RIGHT);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed5), button18, 408, 176);
  gtk_widget_set_size_request (button18, 50, 24);

  image28 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_container_add (GTK_CONTAINER (button18), image28);

  label31 = gtk_label_new (_("ATTENTION !\nsi vous cliquer comfirmer la date saisie sera\nperdue !"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 120, 80);
  gtk_widget_set_size_request (label31, 376, 96);

  image29 = create_pixmap (window5, "gym_monaghan.jpg");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed5), image29, 472, 0);
  gtk_widget_set_size_request (image29, 312, 592);
  gtk_misc_set_alignment (GTK_MISC (image29), 0.21, 0);

  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_button18_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (window5, label29, "label29");
  GLADE_HOOKUP_OBJECT (window5, label30, "label30");
  GLADE_HOOKUP_OBJECT (window5, label33, "label33");
  GLADE_HOOKUP_OBJECT (window5, image9, "image9");
  GLADE_HOOKUP_OBJECT (window5, button10, "button10");
  GLADE_HOOKUP_OBJECT (window5, image7, "image7");
  GLADE_HOOKUP_OBJECT (window5, button9, "button9");
  GLADE_HOOKUP_OBJECT (window5, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window5, label55, "label55");
  GLADE_HOOKUP_OBJECT (window5, button18, "button18");
  GLADE_HOOKUP_OBJECT (window5, image28, "image28");
  GLADE_HOOKUP_OBJECT (window5, label31, "label31");
  GLADE_HOOKUP_OBJECT (window5, image29, "image29");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GdkPixbuf *window6_icon_pixbuf;
  GtkWidget *fixed6;
  GtkWidget *button16;
  GtkWidget *image14;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *button14;
  GtkWidget *image12;
  GtkWidget *image24;
  GtkWidget *button17;
  GtkWidget *image26;
  GtkWidget *label37;
  GtkWidget *label36;
  GtkWidget *label53;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window6, 785, 581);
  gtk_window_set_title (GTK_WINDOW (window6), _("my gym"));
  gtk_window_set_position (GTK_WINDOW (window6), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (window6), FALSE);
  window6_icon_pixbuf = create_pixbuf ("sdsdsds.png");
  if (window6_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window6), window6_icon_pixbuf);
      gdk_pixbuf_unref (window6_icon_pixbuf);
    }

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window6), fixed6);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed6), button16, 16, 656);
  gtk_widget_set_size_request (button16, 74, 29);

  image14 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_container_add (GTK_CONTAINER (button16), image14);

  spinbutton7_adj = gtk_adjustment_new (100, 100, 999, 1, 100, 100);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton7, 120, 56);
  gtk_widget_set_size_request (spinbutton7, 152, 32);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed6), button14, 312, 56);
  gtk_widget_set_size_request (button14, 40, 32);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (button14), image12);

  image24 = create_pixmap (window6, "sportifs.jpg");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed6), image24, 441, 0);
  gtk_widget_set_size_request (image24, 344, 584);
  gtk_misc_set_alignment (GTK_MISC (image24), 1, 0.98);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed6), button17, 24, 56);
  gtk_widget_set_size_request (button17, 74, 29);

  image26 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_container_add (GTK_CONTAINER (button17), image26);

  label37 = gtk_label_new (_("___________________________\n<span foreground=\"#000000\"  size=\"large\">FICHES MEDICALLE</span>\n___________________________"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed6), label37, 24, 72);
  gtk_widget_set_size_request (label37, 344, 88);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);
  gtk_label_set_justify (GTK_LABEL (label37), GTK_JUSTIFY_CENTER);

  label36 = gtk_label_new ("");
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed6), label36, 72, 128);
  gtk_widget_set_size_request (label36, 272, 528);

  label53 = gtk_label_new (_("chercher par ID!"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed6), label53, 128, 24);
  gtk_widget_set_size_request (label53, 145, 33);

  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button17_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window6, button16, "button16");
  GLADE_HOOKUP_OBJECT (window6, image14, "image14");
  GLADE_HOOKUP_OBJECT (window6, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (window6, button14, "button14");
  GLADE_HOOKUP_OBJECT (window6, image12, "image12");
  GLADE_HOOKUP_OBJECT (window6, image24, "image24");
  GLADE_HOOKUP_OBJECT (window6, button17, "button17");
  GLADE_HOOKUP_OBJECT (window6, image26, "image26");
  GLADE_HOOKUP_OBJECT (window6, label37, "label37");
  GLADE_HOOKUP_OBJECT (window6, label36, "label36");
  GLADE_HOOKUP_OBJECT (window6, label53, "label53");

  return window6;
}

GtkWidget*
create_window7 (void)
{
  GtkWidget *window7;
  GtkWidget *fixed7;
  GtkWidget *label44;

  window7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7), _("HI MATE !"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window7), fixed7);

  label44 = gtk_label_new (_("if you could make it here then you are so special\nthis is my first desktop program ever\nso it means a lot to me <3\nmaybe one day, me and you we will reach what \nwe want to reach\nand get back to see this widget and cry a lot XD\nMADE BY COCA !!!"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed7), label44, 48, 32);
  gtk_widget_set_size_request (label44, 328, 432);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7, window7, "window7");
  GLADE_HOOKUP_OBJECT (window7, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window7, label44, "label44");

  return window7;
}

